/* Generate CSP-compatible validators from the pinned local schema registry. */
const fs = require('node:fs');
const path = require('node:path');
const {createRequire} = require('node:module');
const root = path.resolve(__dirname, '..');
const localRequire = createRequire(path.join(root, 'extension/package.json'));
const Ajv = localRequire('ajv/dist/2020').default;
const addFormats = localRequire('ajv-formats');
const standalone = localRequire('ajv/dist/standalone').default;
const ajv = new Ajv({allErrors: true, strict: false, code: {source: true, esm: true}});
addFormats(ajv);
for (const directory of ['vendor/hybrid-discovery-v6.3.6/schemas', 'contracts/offline_slice/v1']) {
  for (const name of fs.readdirSync(path.join(root, directory)).filter(n => n.endsWith('.schema.json'))) {
    ajv.addSchema(JSON.parse(fs.readFileSync(path.join(root, directory, name), 'utf8')));
  }
}
let code = standalone(ajv, {
  validateRaw: 'urn:hybrid-discovery:v6.2:raw-observation:v1',
  validateFrame: 'urn:betting-helper:offline-slice:frame:v1',
  validateContext: 'urn:betting-helper:offline-slice:context:v1',
});
// Standalone Ajv references a few pinned CommonJS runtime helpers. Preserve their
// implementation in static closures so extension CSP needs neither eval nor Node.
const modules = new Map();
const declarations = [];
function embed(name, importer = localRequire) {
  const filename = importer.resolve(name);
  if (modules.has(filename)) return modules.get(filename);
  const identifier = '__runtime' + modules.size;
  modules.set(filename, identifier);
  let source = fs.readFileSync(filename, 'utf8');
  const relativeRequire = createRequire(filename);
  source = source.replace(/require\((["'])([^"']+)\1\)/g, (_all, _quote, specifier) => embed(specifier, relativeRequire));
  if (/\brequire\s*\(/.test(source)) throw new Error('E_OFFLINE_DYNAMIC_RUNTIME_IMPORT');
  declarations.push(`const ${identifier}=(()=>{const exports={};const module={exports};\n${source}\nreturn module.exports;})();`);
  return identifier;
}
code = code.replace(/require\((["'])([^"']+)\1\)/g, (_all, _quote, name) => embed(name));
if (/\brequire\s*\(/.test(code)) throw new Error('E_OFFLINE_DYNAMIC_VALIDATOR_IMPORT');
const output = process.argv[2];
if (!output) throw new Error('E_OFFLINE_VALIDATOR_OUTPUT');
fs.mkdirSync(path.dirname(output), {recursive: true});
fs.writeFileSync(output, '// Generated by tools/build_offline_validators.cjs; do not edit.\n' + declarations.join('\n') + '\n' + code);
