"""Build the live extension and qualify an explicitly selected isolated platform."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any
from uuid import uuid4

if TYPE_CHECKING:
    from moj_discovery.live_config import LiveConfig

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "src")]
WINDOWS_PARENT = Path("/mnt/c/Users/thenam/Documents/BettingHelper-Repair-Chrome")
NATIVE = Path(
    "/mnt/c/Users/thenam/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe"
)
CHROME = Path("/mnt/c/Program Files/Google/Chrome/Application/chrome.exe")
PlatformResult = dict[str, Any]


def validate_platform_choice(selected: str, observed: str) -> None:
    if {"LINUX_CHROME": "linux", "WINDOWS_CHROME_WSL2": "win32"}.get(selected) != observed:
        raise ValueError("E_PLATFORM_SELECTION")


def hashes(directory: Path) -> dict[str, str]:
    return {
        str(p.relative_to(directory)): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(directory.rglob("*"))
        if p.is_file() and not any(q.is_symlink() for q in (p, *p.parents))
    }


def build_live_extension(output: Path) -> tuple[Path, str]:
    """Canonical build owner; generated bytes live only in a fresh private output."""
    from tools.qualify_chrome_indexeddb import _extension_id

    output.mkdir(parents=True, exist_ok=False)
    pnpm, node = shutil.which("pnpm"), shutil.which("node")
    if not pnpm or not node:
        raise RuntimeError("E_PLATFORM_BUILD_RUNTIME")
    subprocess.run(  # noqa: S603 -- fixed local compiler or qualification command.
        [
            pnpm,
            "--dir",
            "extension",
            "exec",
            "tsc",
            "-p",
            "tsconfig.live.json",
            "--moduleDetection",
            "legacy",
            "--outDir",
            str(output / "compiled"),
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        timeout=60,
    )  # noqa: S603
    extension = output / "extension"
    modules = ["canonical.js", "errors.js", "storage/durable_idb.js"]
    modules += [
        "live/" + p.stem + ".js" for p in sorted((ROOT / "extension/src/live").glob("*.ts"))
    ]
    for name in modules:
        target = extension / "src" / name
        target.parent.mkdir(parents=True, exist_ok=True)
        data = (output / "compiled/src" / name).read_text()
        if name == "canonical.js":
            data = data.replace('from "canonicalize"', 'from "./canonicalize.js"')
        target.write_text(data)
    shutil.copy2(
        ROOT / "extension/node_modules/canonicalize/lib/canonicalize.js",
        extension / "src/canonicalize.js",
    )
    for name in ("panel.html", "workspace.html", "panel.css"):
        shutil.copy2(ROOT / "extension/src/live" / name, extension / "src/live" / name)
    shutil.copy2(ROOT / "extension/manifest.live.json", extension / "manifest.json")
    generator = (
        (ROOT / "tools/build_offline_validators.cjs")
        .read_text()
        .replace(
            "const root = path.resolve(__dirname, '..');",
            "const root = " + json.dumps(str(ROOT)) + ";",
        )
        .replace(
            "['vendor/hybrid-discovery-v6.3.6/schemas', 'contracts/offline_slice/v1']",
            "['contracts/live_readonly/v1']",
        )
    )
    start = generator.index("let code = standalone(ajv, {")
    end = generator.index("});", start) + 3
    mapping = {
        "validate" + name: "urn:betting-helper:live-records:v1#/$defs/" + name
        for name in (
            "MarketBook",
            "ProviderState",
            "FixtureBinding",
            "BindingChange",
            "HealthChange",
            "LiveEvent",
        )
    }
    mapping["validateFrame"] = "urn:betting-helper:live-wire:v1"
    generator = (
        generator[:start]
        + "let code=standalone(ajv,"
        + json.dumps(mapping)
        + ");"
        + generator[end:]
    )
    generator = generator.replace(
        "Generated by tools/build_offline_validators.cjs",
        "Generated by tools/qualify_live_platform.py",
    )
    subprocess.run(  # noqa: S603 -- fixed local compiler or qualification command.
        [node, "-", str(extension / "live-validators.js")],
        input=generator,
        text=True,
        cwd=ROOT,
        check=True,
        capture_output=True,
        timeout=30,
    )  # noqa: S603
    worker = extension / "src/live/background.js"
    worker.write_text(
        "import * as schema from '../../live-validators.js';\n"
        + worker.read_text()
        + "\nstartLiveWorkspace({record:(v,k)=>schema['validate'+k](v),"
        "frame:schema.validateFrame});\n"
    )
    (output / "build-hashes.json").write_text(json.dumps(hashes(extension), indent=2))
    manifest = json.loads((extension / "manifest.json").read_text())
    return extension, "chrome-extension://" + _extension_id(manifest["key"])


def native_owner(configuration: Path) -> None:
    """Native handle owns one job. Never kill by an unverified PID or image name."""
    import ctypes
    from ctypes import wintypes

    from tools.native_environment_probe import observe, observe_handle, save

    if sys.platform != "win32":
        raise RuntimeError("E_PLATFORM_NATIVE_REQUIRED")
    config = json.loads(configuration.read_text())
    case = Path(config["workspace"])
    invocation = [
        sys.executable,
        "-I",
        str(ROOT / "tools/native_environment_probe.py"),
        "browser-leader",
        str(configuration),
    ]
    kernel = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel.OpenProcess.argtypes = [wintypes.DWORD, wintypes.BOOL, wintypes.DWORD]
    kernel.OpenProcess.restype = wintypes.HANDLE
    kernel.WaitForSingleObject.argtypes = [wintypes.HANDLE, wintypes.DWORD]
    kernel.CloseHandle.argtypes = [wintypes.HANDLE]
    handles: list[Any] = []
    with (case / "leader.stdout").open("wb") as out, (case / "leader.stderr").open("wb") as err:
        leader = subprocess.Popen(invocation, stdout=out, stderr=err)  # noqa: S603 -- own retained leader; stdin inherited privately.
    try:
        deadline = time.monotonic() + 40
        while not all((case / p).is_file() for p in ("node-ready.json", "offline-ready.json")):
            if (
                leader.poll() is not None
                or time.monotonic() > deadline
                or (case / "pipe-error.json").exists()
            ):
                raise RuntimeError("E_PLATFORM_NATIVE_READY")
            time.sleep(0.05)
        node = json.loads((case / "node-ready.json").read_text())
        ready = json.loads((case / "offline-ready.json").read_text())
        if node["node"]["pid"] != ready["node_pid"] or not node["job_kill_on_close"]:
            raise RuntimeError("E_PLATFORM_NATIVE_PARENT")
        for pid in (ready["node_pid"], ready["pid"]):
            handle = kernel.OpenProcess(0x1000 | 0x100000, False, pid)
            if not handle:
                raise RuntimeError("E_PLATFORM_NATIVE_HANDLE")
            handles.append(handle)
        chrome = observe_handle(ready["pid"], int(handles[1]), config["command"])
        if chrome["cim"]["ParentProcessId"] != ready["node_pid"]:
            raise RuntimeError("E_PLATFORM_CHROME_PARENT")
        save(
            case / "identity.json",
            {
                "system": sys.platform,
                "leader": observe(leader),
                "browser": chrome,
                "node": node,
                "ready": ready,
            },
        )
        deadline = time.monotonic() + 180
        while not (case / "stop-owner").exists():
            if leader.poll() is not None or time.monotonic() > deadline:
                raise RuntimeError("E_PLATFORM_OWNER_DEADLINE")
            time.sleep(0.05)
    finally:
        if leader.poll() is None:
            leader.kill()  # Own Popen handle; Windows job terminates inherited members.
        code = leader.wait(timeout=10)
        waits = [kernel.WaitForSingleObject(h, 10000) for h in handles]
        for handle in handles:
            kernel.CloseHandle(handle)
        save(
            case / "termination.json",
            {
                "mechanism": "WINDOWS_JOB_KILL_ON_CONTROLLER_TERMINATION",
                "leader_exit": code,
                "observed_handle_waits": waits,
                "all_observed_handles_signaled": len(waits) == 2 and waits == [0, 0],
            },
        )
        if waits != [0, 0]:
            raise RuntimeError("E_PLATFORM_NATIVE_CLEANUP")


class WindowsBrowser:
    """Fixed native profile, private stdin and a bounded handle-owning controller."""

    def __init__(self, extension: Path, origin: str, driver: Path, profile: Path | None = None):
        from tools.qualify_chrome_indexeddb import _pipe_browser_command
        from tools.run_environment_qualification import winpath

        if not all(p.is_file() for p in (NATIVE, CHROME, driver)):
            raise RuntimeError("WAITING_PLATFORM")
        self.workspace = WINDOWS_PARENT / ("part-b-platform-" + str(uuid4()))
        self.workspace.mkdir(parents=True, exist_ok=False)
        copied = self.workspace / "extension"
        shutil.copytree(extension, copied)
        shutil.copy2(driver, self.workspace / "chrome_pipe.cjs")
        owned_binding = {"origin": origin, "source": str(extension.resolve())}
        if profile is None:
            profile = self.workspace / "profile"
            profile.mkdir()
            (profile / ".part-b-owned.json").write_text(json.dumps(owned_binding))
        elif (
            profile.name != "profile"
            or profile.parent.parent != WINDOWS_PARENT
            or not profile.parent.name.startswith("part-b-platform-")
            or any(p.is_symlink() for p in (profile, *profile.parents))
            or json.loads((profile / ".part-b-owned.json").read_text()) != owned_binding
            or json.loads((profile.parent / "termination.json").read_text())[
                "all_observed_handles_signaled"
            ]
            is not True
        ):
            raise ValueError("E_PLATFORM_PROFILE_OWNERSHIP")
        self.profile = profile
        node = NATIVE.parent.parent / "node/bin/node.exe"
        command = _pipe_browser_command(CHROME, profile)
        command[0] = winpath(CHROME)
        command = [
            "--user-data-dir=" + winpath(profile) if p.startswith("--user-data-dir=") else p
            for p in command
        ]
        configuration = self.workspace / "input.json"
        configuration.write_text(
            json.dumps(
                {
                    "workspace": winpath(self.workspace),
                    "origin": origin,
                    "extension": winpath(copied),
                    "command": command,
                    "offline": True,
                    "transport": "pipe",
                    "node": winpath(node),
                    "script": winpath(self.workspace / "chrome_pipe.cjs"),
                    "input_path": winpath(configuration),
                }
            )
        )
        (self.workspace / "start.json").write_text("{}")
        (self.workspace / "temp").mkdir()
        environment = {
            "PATH": "/usr/bin:/bin",
            "SystemRoot": "C:\\Windows",
            "WINDIR": "C:\\Windows",
            "TEMP": winpath(self.workspace / "temp"),
            "TMP": winpath(self.workspace / "temp"),
        }
        with (
            (self.workspace / "owner.stdout").open("wb") as out,
            (self.workspace / "owner.stderr").open("wb") as err,
        ):
            self.owner = subprocess.Popen(  # noqa: S603 -- fixed native controller.
                [
                    str(NATIVE),
                    "-I",
                    winpath(Path(__file__)),
                    "--native-owner",
                    winpath(configuration),
                ],
                stdin=subprocess.PIPE,
                stdout=out,
                stderr=err,
                env=environment,
            )  # noqa: S603 -- fixed native controller, no secret inheritance.
        self.index = 0
        try:
            self.ready = self.wait("identity.json")
            validate_platform_choice("WINDOWS_CHROME_WSL2", self.ready["system"])
            if self.ready["browser"]["sha256"] != hashlib.sha256(CHROME.read_bytes()).hexdigest():
                raise RuntimeError("E_PLATFORM_BINARY")
        except BaseException:
            self.close()
            raise

    def wait(self, name: str) -> dict[str, Any]:
        deadline = time.monotonic() + 50
        while not (self.workspace / name).is_file():
            if self.owner.poll() is not None or (self.workspace / "pipe-error.json").exists():
                raise RuntimeError("E_PLATFORM_BROWSER_PROBE")
            if time.monotonic() > deadline:
                raise RuntimeError("E_PLATFORM_BROWSER_TIMEOUT")
            time.sleep(0.03)
        return json.loads((self.workspace / name).read_text())  # type: ignore[no-any-return]

    def command(self, request: dict[str, Any]) -> dict[str, Any]:
        assert self.owner.stdin is not None
        self.owner.stdin.write(json.dumps(request).encode() + b"\n")
        self.owner.stdin.flush()
        self.index += 1
        return self.wait(f"offline-result-{self.index}.json")["result"]  # type: ignore[no-any-return]

    def close(self) -> None:
        (self.workspace / "stop-owner").touch(exist_ok=True)
        self.owner.wait(timeout=55)
        if self.owner.stdin:
            self.owner.stdin.close()
        result = json.loads((self.workspace / "termination.json").read_text())
        if not result["all_observed_handles_signaled"]:
            raise RuntimeError("E_PLATFORM_CLEANUP")


def qualify_platform(config: LiveConfig, output: Path) -> PlatformResult:
    from moj_discovery.live_intent import source_tree_hash

    output = output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    source_hash = source_tree_hash()
    platform = config.public["runtime"]["platform"]
    validate_platform_choice(
        platform, {"WINDOWS_CHROME_WSL2": "win32", "LINUX_CHROME": "linux"}.get(platform, "")
    )
    environment = {
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        "HOME": "/home/thenam176",
        "LANG": "C.UTF-8",
        "PB_PLATFORM": platform,
    }
    command = [
        sys.executable,
        "-m",
        "pytest",
        "-q",
        "tests/live/test_local_bridge.py",
        "--basetemp=" + str(output / "observations"),
    ]
    with (output / "checks.log").open("wb") as log:
        completed = subprocess.run(  # noqa: S603 -- fixed local compiler or qualification command.
            command, cwd=ROOT, env=environment, stdout=log, stderr=subprocess.STDOUT, timeout=300
        )  # noqa: S603
    observed_files = [
        p
        for p in (output / "observations").glob("*/observed-bridge.json")
        if not p.parent.is_symlink()
    ]
    observed = json.loads(observed_files[0].read_text()) if len(observed_files) == 1 else None
    passed = (
        completed.returncode == 0
        and observed is not None
        and observed["platform"] == platform
        and observed["bound_addresses"] == ["127.0.0.1"]
        and observed["real_provider_attempts"] == 0
        and observed["operator_observed"] is False
        and source_tree_hash() == source_hash
        and (observed_files[0].parent / "observed-termination.json").is_file()
    )
    result = {
        "status": "PASS" if passed else "WAITING_PLATFORM",
        "platform": platform,
        "source_tree_sha256": source_hash,
        "config_sha256": config.sha256,
        "command": command,
        "exit": completed.returncode,
        "evidence": hashes(output),
        "source_kind": "SYNTHETIC",
        "operator_observed": False,
        "real_provider_attempts": 0,
        "sleep_wake": "NOT_OBSERVED",
        "physical_power_loss": "NOT_OBSERVED",
        "test_source_sha256": hashlib.sha256(
            (ROOT / "tests/live/test_local_bridge.py").read_bytes()
        ).hexdigest(),
    }
    (output / "result.json").write_text(json.dumps(result, indent=2))
    return result


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "--native-owner":
        native_owner(Path(sys.argv[2]))
    else:
        parser = argparse.ArgumentParser(description=__doc__)
        parser.add_argument("--config", type=Path, required=True)
        parser.add_argument("--output", type=Path, required=True)
        args = parser.parse_args()
        from moj_discovery.live_config import load_live_config

        outcome = qualify_platform(load_live_config(args.config), args.output)
        print(outcome["status"])
        raise SystemExit(0 if outcome["status"] == "PASS" else 2)
